// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include <Arduino.h>

void ButtonEin_Clicked(lv_event_t * e)
{
	// Your code here
  digitalWrite(32, HIGH);
}

void ButtonAus_Clicked(lv_event_t * e)
{
	// Your code here
  digitalWrite(32, LOW);
}
