// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonEin = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonEin, 100);
    lv_obj_set_height(ui_ButtonEin, 50);
    lv_obj_set_x(ui_ButtonEin, 0);
    lv_obj_set_y(ui_ButtonEin, -46);
    lv_obj_set_align(ui_ButtonEin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonEin, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ButtonEin);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -19);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Ein");

    ui_ButtonAus = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonAus, 100);
    lv_obj_set_height(ui_ButtonAus, 50);
    lv_obj_set_x(ui_ButtonAus, 0);
    lv_obj_set_y(ui_ButtonAus, 35);
    lv_obj_set_align(ui_ButtonAus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ButtonAus);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 2);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Aus");

    lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonEin, ui_event_ButtonEin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonAus, ui_event_ButtonAus, LV_EVENT_ALL, NULL);

}
