// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: RobiTheWinnerDisplay

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ButtonOpenSettingClicked(lv_event_t * e);
void ButtonStartGameClicked(lv_event_t * e);
void ButtonSettingsOkayClicked(lv_event_t * e);
void ButtonTakeOneClicked(lv_event_t * e);
void ButtonTakeTwoClicked(lv_event_t * e);
void ButtonTakeThreeClicked(lv_event_t * e);
void ButtonGameFinshedClick(lv_event_t * e);
void StartBallOutputClicked(lv_event_t * e);
void BallLiftStartClicked(lv_event_t * e);
void BallLiftStopClicked(lv_event_t * e);
void BallOutputSpeedChanged(lv_event_t * e);
void BallLiftSpeedChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
