// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: RobiTheWinnerDisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_StartGameScreen
void ui_StartGameScreen_screen_init(void);
lv_obj_t * ui_StartGameScreen;
void ui_event_Image2(lv_event_t * e);
lv_obj_t * ui_Image2;
lv_obj_t * ui_LabelBallsToPlay;
lv_obj_t * ui_LabelTextBallsToPlay;
lv_obj_t * ui_Label9;
void ui_event_ButtonChangeBallAmount(lv_event_t * e);
lv_obj_t * ui_ButtonChangeBallAmount;
lv_obj_t * ui_LabelChangeAmountOfBall;
void ui_event_ButtonPlay(lv_event_t * e);
lv_obj_t * ui_ButtonPlay;
lv_obj_t * ui_LabelButtonPlay;
lv_obj_t * ui_LabelWinsAlways;
lv_obj_t * ui_LabelInstructions;
// CUSTOM VARIABLES


// SCREEN: ui_SettingScreen
void ui_SettingScreen_screen_init(void);
lv_obj_t * ui_SettingScreen;
lv_obj_t * ui_Image1;
void ui_event_SliderBallAmount(lv_event_t * e);
lv_obj_t * ui_SliderBallAmount;
lv_obj_t * ui_LabelBallAmountText;
lv_obj_t * ui_LabelNumberOfBall;
void ui_event_ButtonlessBall(lv_event_t * e);
lv_obj_t * ui_ButtonlessBall;
lv_obj_t * ui_LabelWeniger;
void ui_event_ButtonMoreBall(lv_event_t * e);
lv_obj_t * ui_ButtonMoreBall;
lv_obj_t * ui_LabelMehr;
void ui_event_ButtonSettingOk(lv_event_t * e);
lv_obj_t * ui_ButtonSettingOk;
lv_obj_t * ui_LabelButtonSettingOk;
// CUSTOM VARIABLES


// SCREEN: ui_PlayScreen
void ui_PlayScreen_screen_init(void);
lv_obj_t * ui_PlayScreen;
lv_obj_t * ui_Label14;
void ui_event_ButtonOneBall(lv_event_t * e);
lv_obj_t * ui_ButtonOneBall;
lv_obj_t * ui_LabelButtonOneBall;
void ui_event_ButtonTwoBall(lv_event_t * e);
lv_obj_t * ui_ButtonTwoBall;
lv_obj_t * ui_LabelButtonTwoBall;
void ui_event_ButtonThreeBall(lv_event_t * e);
lv_obj_t * ui_ButtonThreeBall;
lv_obj_t * ui_LabelButtonThreeBall;
lv_obj_t * ui_LabelRobiSpielt;
lv_obj_t * ui_LabelRobiBallAmount;
lv_obj_t * ui_LabelBallRemainingInGameText;
lv_obj_t * ui_LabelRemainingInGame;
void ui_event_ButtonGameEnd(lv_event_t * e);
lv_obj_t * ui_ButtonGameEnd;
lv_obj_t * ui_Label26;
void ui_event_Image3(lv_event_t * e);
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES


// SCREEN: ui_TestScreen
void ui_TestScreen_screen_init(void);
lv_obj_t * ui_TestScreen;
void ui_event_Image5(lv_event_t * e);
lv_obj_t * ui_Image5;
lv_obj_t * ui_Container1;
lv_obj_t * ui_SpinBoxTestBallAmount;
void ui_event_ButtonTestBallAmountDec(lv_event_t * e);
lv_obj_t * ui_ButtonTestBallAmountDec;
lv_obj_t * ui_LabelTestBallAmountDec;
void ui_event_ButtonTestBallAmountInc(lv_event_t * e);
lv_obj_t * ui_ButtonTestBallAmountInc;
lv_obj_t * ui_LabelTestBallAmountInc;
void ui_event_ButtonStartBallOutput(lv_event_t * e);
lv_obj_t * ui_ButtonStartBallOutput;
lv_obj_t * ui_LabelStartBallOutput;
void ui_event_ButtonStartBallLift(lv_event_t * e);
lv_obj_t * ui_ButtonStartBallLift;
lv_obj_t * ui_LabelStartBallLift;
void ui_event_ButtonStopBallLift(lv_event_t * e);
lv_obj_t * ui_ButtonStopBallLift;
lv_obj_t * ui_LabelStopBallLift;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TestScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TestScreen_screen_init);
        _ui_screen_change(&ui_TestScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TestScreen_screen_init);
        _ui_screen_delete(&ui_StartGameScreen);
    }
}

void ui_event_ButtonChangeBallAmount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingScreen_screen_init);
        _ui_screen_delete(&ui_StartGameScreen);
        ButtonOpenSettingClicked(e);
    }
}

void ui_event_ButtonPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PlayScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PlayScreen_screen_init);
        _ui_screen_delete(&ui_StartGameScreen);
        ButtonStartGameClicked(e);
    }
}

void ui_event_SliderBallAmount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelBallsToPlay, target, "", "");
        _ui_slider_set_text_value(ui_LabelNumberOfBall, target, "", "");
    }
}

void ui_event_ButtonlessBall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_slider_increment(ui_SliderBallAmount, -4, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_slider_increment(ui_SliderBallAmount, -4, LV_ANIM_ON);
    }
}

void ui_event_ButtonMoreBall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_slider_increment(ui_SliderBallAmount, 4, LV_ANIM_ON);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_slider_increment(ui_SliderBallAmount, 4, LV_ANIM_ON);
    }
}

void ui_event_ButtonSettingOk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartGameScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StartGameScreen_screen_init);
        _ui_screen_delete(&ui_SettingScreen);
        ButtonSettingsOkayClicked(e);
    }
}

void ui_event_ButtonOneBall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonTakeOneClicked(e);
    }
}

void ui_event_ButtonTwoBall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonTakeTwoClicked(e);
    }
}

void ui_event_ButtonThreeBall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ButtonTakeThreeClicked(e);
    }
}

void ui_event_ButtonGameEnd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartGameScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StartGameScreen_screen_init);
        _ui_screen_delete(&ui_PlayScreen);
        ButtonGameFinshedClick(e);
    }
}

void ui_event_Image3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartGameScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StartGameScreen_screen_init);
        _ui_screen_delete(&ui_PlayScreen);
    }
}

void ui_event_Image5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartGameScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StartGameScreen_screen_init);
        _ui_screen_delete(&ui_TestScreen);
    }
}

void ui_event_ButtonTestBallAmountDec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinBoxTestBallAmount, -1);
    }
}

void ui_event_ButtonTestBallAmountInc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinBoxTestBallAmount, 1);
    }
}

void ui_event_ButtonStartBallOutput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartBallOutputClicked(e);
    }
}

void ui_event_ButtonStartBallLift(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ButtonStartBallLift, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ButtonStopBallLift, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        BallLiftStartClicked(e);
    }
}

void ui_event_ButtonStopBallLift(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ButtonStartBallLift, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ButtonStopBallLift, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        BallLiftStopClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_StartGameScreen_screen_init();
    ui_SettingScreen_screen_init();
    ui_PlayScreen_screen_init();
    ui_TestScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_StartGameScreen);
}
