// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: RobiTheWinnerDisplay

#include "ui.h"

void ButtonOpenSettingClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonStartGameClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonSettingsOkayClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonTakeOneClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonTakeTwoClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonTakeThreeClicked(lv_event_t * e)
{
	// Your code here
}

void ButtonGameFinshedClick(lv_event_t * e)
{
	// Your code here
}

void StartBallOutputClicked(lv_event_t * e)
{
	// Your code here
}

void BallLiftStartClicked(lv_event_t * e)
{
	// Your code here
}

void BallLiftStopClicked(lv_event_t * e)
{
	// Your code here
}

void BallOutputSpeedChanged(lv_event_t * e)
{
	// Your code here
}

void BallLiftSpeedChanged(lv_event_t * e)
{
	// Your code here
}
