// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: RobiTheWinnerDisplay

#include "ui.h"

void ui_StartGameScreen_screen_init(void)
{
    ui_StartGameScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartGameScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_StartGameScreen, &ui_font_SanSerif17, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_StartGameScreen);
    lv_img_set_src(ui_Image2, &ui_img_arduinoeasy_logoprint_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_align(ui_Image2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBallsToPlay = lv_label_create(ui_StartGameScreen);
    lv_obj_set_width(ui_LabelBallsToPlay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBallsToPlay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBallsToPlay, -11);
    lv_obj_set_y(ui_LabelBallsToPlay, 22);
    lv_obj_set_align(ui_LabelBallsToPlay, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelBallsToPlay, "21");
    lv_obj_set_style_text_font(ui_LabelBallsToPlay, &ui_font_SansSerif25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTextBallsToPlay = lv_label_create(ui_StartGameScreen);
    lv_obj_set_width(ui_LabelTextBallsToPlay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTextBallsToPlay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTextBallsToPlay, 17);
    lv_obj_set_y(ui_LabelTextBallsToPlay, 27);
    lv_label_set_text(ui_LabelTextBallsToPlay, "Wir spielen mit ");

    ui_Label9 = lv_label_create(ui_StartGameScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 30);
    lv_obj_set_y(ui_Label9, -83);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Bällen");

    ui_ButtonChangeBallAmount = lv_btn_create(ui_StartGameScreen);
    lv_obj_set_width(ui_ButtonChangeBallAmount, 73);
    lv_obj_set_height(ui_ButtonChangeBallAmount, 50);
    lv_obj_set_x(ui_ButtonChangeBallAmount, 109);
    lv_obj_set_y(ui_ButtonChangeBallAmount, -89);
    lv_obj_set_align(ui_ButtonChangeBallAmount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonChangeBallAmount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonChangeBallAmount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelChangeAmountOfBall = lv_label_create(ui_ButtonChangeBallAmount);
    lv_obj_set_width(ui_LabelChangeAmountOfBall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChangeAmountOfBall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelChangeAmountOfBall, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChangeAmountOfBall, "Ändern");

    ui_ButtonPlay = lv_btn_create(ui_StartGameScreen);
    lv_obj_set_width(ui_ButtonPlay, 120);
    lv_obj_set_height(ui_ButtonPlay, 50);
    lv_obj_set_x(ui_ButtonPlay, 1);
    lv_obj_set_y(ui_ButtonPlay, -2);
    lv_obj_set_align(ui_ButtonPlay, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ButtonPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonPlay, lv_color_hex(0x00959C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelButtonPlay = lv_label_create(ui_ButtonPlay);
    lv_obj_set_width(ui_LabelButtonPlay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonPlay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonPlay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonPlay, "Spiel starten");

    ui_LabelWinsAlways = lv_label_create(ui_StartGameScreen);
    lv_obj_set_width(ui_LabelWinsAlways, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWinsAlways, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWinsAlways, 0);
    lv_obj_set_y(ui_LabelWinsAlways, 33);
    lv_obj_set_align(ui_LabelWinsAlways, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWinsAlways, "ROBI GEWINNT IMMER");
    lv_obj_set_style_text_color(ui_LabelWinsAlways, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWinsAlways, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelInstructions = lv_label_create(ui_StartGameScreen);
    lv_obj_set_width(ui_LabelInstructions, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelInstructions, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelInstructions, 0);
    lv_obj_set_y(ui_LabelInstructions, 1);
    lv_obj_set_align(ui_LabelInstructions, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelInstructions, "Gewünschte Anzahl Bälle ins Magazine \nlegen und Spiel starten. Achtung:");

    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonChangeBallAmount, ui_event_ButtonChangeBallAmount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPlay, ui_event_ButtonPlay, LV_EVENT_ALL, NULL);

}
