// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_ButtonOn(lv_event_t * e);
extern lv_obj_t * ui_ButtonOn;
void ui_event_LabelOn(lv_event_t * e);
extern lv_obj_t * ui_LabelOn;
void ui_event_ButtonOff(lv_event_t * e);
extern lv_obj_t * ui_ButtonOff;
extern lv_obj_t * ui_LabelOff;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
