// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: TestDisplay

#include "ui.h"

void ButtonOn_Clicked(lv_event_t * e)
{
	// Your code here
}

void ButtonOff_Clicked(lv_event_t * e)
{
	// Your code here
}
