// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonOn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonOn, 100);
    lv_obj_set_height(ui_ButtonOn, 50);
    lv_obj_set_x(ui_ButtonOn, 0);
    lv_obj_set_y(ui_ButtonOn, -46);
    lv_obj_set_align(ui_ButtonOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOn = lv_label_create(ui_ButtonOn);
    lv_obj_set_width(ui_LabelOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOn, 5);
    lv_obj_set_y(ui_LabelOn, -1);
    lv_obj_set_align(ui_LabelOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOn, "On");

    ui_ButtonOff = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonOff, 100);
    lv_obj_set_height(ui_ButtonOff, 50);
    lv_obj_set_x(ui_ButtonOff, 0);
    lv_obj_set_y(ui_ButtonOff, 35);
    lv_obj_set_align(ui_ButtonOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOff = lv_label_create(ui_ButtonOff);
    lv_obj_set_width(ui_LabelOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOff, 2);
    lv_obj_set_y(ui_LabelOff, 1);
    lv_obj_set_align(ui_LabelOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOff, "Off");

    lv_obj_add_event_cb(ui_LabelOn, ui_event_LabelOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOn, ui_event_ButtonOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOff, ui_event_ButtonOff, LV_EVENT_ALL, NULL);

}
