// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: TestDisplay

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_arduinoeasy_logoprint_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 151
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image1, 12);
    lv_obj_set_y(ui_Image1, 81);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonOn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonOn, 100);
    lv_obj_set_height(ui_ButtonOn, 50);
    lv_obj_set_x(ui_ButtonOn, 4);
    lv_obj_set_y(ui_ButtonOn, -56);
    lv_obj_set_align(ui_ButtonOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOn = lv_label_create(ui_ButtonOn);
    lv_obj_set_width(ui_LabelOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOn, "On");

    ui_ButtonOff = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonOff, 100);
    lv_obj_set_height(ui_ButtonOff, 50);
    lv_obj_set_x(ui_ButtonOff, 4);
    lv_obj_set_y(ui_ButtonOff, 13);
    lv_obj_set_align(ui_ButtonOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelOff = lv_label_create(ui_ButtonOff);
    lv_obj_set_width(ui_LabelOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOff, 0);
    lv_obj_set_y(ui_LabelOff, 1);
    lv_obj_set_align(ui_LabelOff, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOff, "Off");

    lv_obj_add_event_cb(ui_LabelOn, ui_event_LabelOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOn, ui_event_ButtonOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOff, ui_event_ButtonOff, LV_EVENT_ALL, NULL);

}
